version: '3.8'

services:
  cypress:
    image: cypress/included:13.5.1 
    volumes:
     - .:/e2e 
    working_dir: /e2e 
    command: ["cypress", "run"] 
    environment:
      - CYPRESS_baseUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
    networks:
      - cypress_network

networks:
  cypress_network:
